{{- if and .Values.adminToken.value (not .Values.adminToken.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "status-aggregator.secretName" . }}
  labels:
    {{- include "status-aggregator.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.adminToken.existingSecretKey }}: {{ .Values.adminToken.value | b64enc | quote }}
{{- end }}
